### ISSUE TITLE
Provide iOS framework download

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-notificationhubs#24]
As discussed in https://github.com/Azure/azure-mobile-services/issues/812 the Messaging Framework is no longer included in the iOS SDK downloads for mobile services/apps. iOS users need a convenient way to obtain the framework, such as a zip download from http://azure.github.io.

**Comment by marchv** [comment]
I was happy to find AzureSDK-iOS available as a pod. But then I realized it was without Messaging Framework and so useless in my context :S

Any idea if this will be included again? At least a little bit hard to understand why it isn't any longer?

If to be included again any approx ETA?

Thanks :)

**Comment by brannon** [comment]
Hey, this issue is pretty old, but we recently updated the iOS SDK to fix a bug and published the resulting framework as a GitHub Release:
https://github.com/Azure/azure-notificationhubs/releases/tag/viOS-2.0.1

We also make the .zip file available as a direct download:
http://aka.ms/aznh-ios-sdk

Hopefully this is a step in the right direction.

We'll look into supporting Cocoa Pods in the future, but as of right now do not have an ETA.
